### ISSUE TITLE
Vim Command Mode support 

### ISSUE THREAD

**Issue by Huxisher** [sayanarijit/xplr#122]
being able to use vim command is useful! 
i know there is key binds : )
but with command we can use it for many things 
for example
:help
:delete
:rename
:colorscheme -> set ui color!
Etc...

**Comment by sayanarijit** [comment]
Actually I think it's useful in vim because you can do scripting with the commands. The xplr alternative to vim commands is [messages](https://github.com/sayanarijit/xplr/wiki/Messages). Hence, I don't think having a separate concept of command will be very beneficial for xplr.

Although, if you prefer commands more than key bindings, you hack it.

```yaml
modes:
  builtin:
    default:
      key_bindings:
        on_key:
          ':':
            help: command
            messages:
              - SwitchMode: command
              - BufferInput: ""
  custom:
    command:
      key_bindings:
        on_key:
          backspace:
            help: remove last character
            messages:
              - RemoveInputBufferLastCharacter
          ctrl-w:
            help: remove last word
            messages:
              - RemoveInputBufferLastWord

          ctrl-u:
            help: remove line
            messages:
              - SetInputBuffer: ""
          esc:
            help: cancel
            messages:
              - SwitchMode: default
          enter:
            help: execute
            messages:
              - BashExec: |
                  CMD="${XPLR_INPUT_BUFFER:?}"
                  case "$CMD" in
                    terminal)
                      bash
                      ;;
                    help)
                      less "${XPLR_PIPE_GLOBAL_HELP_MENU_OUT:?}"
                      ;;
                    *)
                      echo "LogError: invalid command $CMD" >> "${XPLR_PIPE_MSG_IN:?}"
                      ;;
                  esac
              - SwitchMode: default
        default:
          messages:
            - BufferInputFromKey
```
You can of course also integrate `fzf` into it to fuzzy search commands.

**Comment by sayanarijit** [comment]
Another simplified version is

```yaml
modes:
  builtin:
    default:
      key_bindings:
        on_key:
          ':':
            help: command
            messages:
              - SwitchMode: command
              - BufferInput: ""
  custom:
    command:
      key_bindings:
        on_key:
          backspace:
            help: remove last character
            messages:
              - RemoveInputBufferLastCharacter
          ctrl-w:
            help: remove last word
            messages:
              - RemoveInputBufferLastWord

          ctrl-u:
            help: remove line
            messages:
              - SetInputBuffer: ""
          esc:
            help: cancel
            messages:
              - SwitchMode: default
          enter:
            help: execute
            messages:
              - BashExec: |
                  echo "${XPLR_INPUT_BUFFER:?}" >> "${XPLR_PIPE_MSG_IN:?}"
              - SwitchMode: default
        default:
          messages:
            - BufferInputFromKey
```

Using this config, you can make xplr handle any message. e.g. `:FocusNext`, `:SelectAll` etc.
