### ISSUE TITLE
overwrite config issue

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#68]
Hey @sayanarijit, just wanted to follow-up on this, it generally works well but I found two cases to consider:

1. It seems impossible to override `prefix` and `suffix` of `*_ui` options, unless I'm doing something wrong? (I simply want to add spaces on both sides, but any change doesn't seem to be reflected)

```yaml
general:
  default_ui:
    prefix: "   "
    suffix: " "
  focus_ui:
    prefix: "▸[ "
    suffix: " ]"
    style:
      fg: Cyan
  selection_ui:
    prefix: " { "
    suffix: " }"
```

2. It's probably impossible to override arrays, so e.g. I wanted to remove the third column "index", but I guess the only option for me would be to override entire `header.cols` and `row.cols`. I don't have a good alternative right away, so just curious if you have some good ideas 🤔

_Originally posted by @maximbaz in https://github.com/sayanarijit/xplr/issues/47#issuecomment-819923624_

**Comment by maximbaz** [comment]
Thanks for super fast PR as usual! This had an unfortunate side effect that selection color (bright green, when you press space) no longer shows on top of folders and symlinks, i.e. folder and symlink colors still remain even if file was selected with space).

**Comment by maximbaz** [comment]
Maybe it's a bigger problem with color overrides in fact, let me give you an example that I'm trying to make to work. All of the styles below don't seem to be applied:

```yaml
general:
  default_ui:
    prefix: "   "
    suffix: " "
  focus_ui:
    prefix: "▸[ "
    suffix: " ]"
    style:
      fg: Cyan
  selection_ui:
    prefix: " { "
    suffix: " }"

node_types:
  directory:
    style:
      fg: Blue
  file:
    style:
      add_modifier:
        bits: 2
```
